### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by Glup3** [TeamLumi/luminescent-team#42]
I would love to see TypeScript support. I always feel on the edge to write untyped JavaScript. Everything is so much more fragile and I feel like JavaScript is slowing me more down than TypeScript.

**Comment by Denmark14** [comment]
I understand the desire, but I feel like this would be wasted effort now that we're nearing completion of the app. While it may benefit yourself directly for the application to be converted to TypeScript, it is important to note that TypeScript itself can also be fragile and is still to this day quite buggy in my experience. 

If it came about that a full rewrite of the app in order to preserve types was necessary, I would opt for a strongly typed language over TypeScript. 

To expand on what I said about nearing completion. As of today, we have the Pokedex to finish, build tasks to create and an interactive route map to develop.  I believe anything further than this would clutter the site and be better served on a separate web app.
